name: pokecatching
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/font.ttf
  assets:
    - assets/icon/icon.png
    - assets/bottons/pokeballred.png
  uses-material-design: true
